// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBarSearch: typeof import('./resources/js/@core/components/AppBarSearch.vue')['default']
    AppCardActions: typeof import('./resources/js/@core/components/AppCardActions.vue')['default']
    AppCardCode: typeof import('./resources/js/@core/components/AppCardCode.vue')['default']
    AppDateTimePicker: typeof import('./resources/js/@core/components/AppDateTimePicker.vue')['default']
    AppOtpInput: typeof import('./resources/js/@core/components/AppOtpInput.vue')['default']
    AppPricing: typeof import('./resources/js/@core/components/AppPricing.vue')['default']
    AppSearchHeader: typeof import('./resources/js/@core/components/AppSearchHeader.vue')['default']
    BuyNow: typeof import('./resources/js/@core/components/BuyNow.vue')['default']
    CardAddEditDialog: typeof import('./resources/js/@core/components/CardAddEditDialog.vue')['default']
    CardStatisticsHorizontal: typeof import('./resources/js/@core/components/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./resources/js/@core/components/CardStatisticsVertical.vue')['default']
    CardStatisticsVerticalSimple: typeof import('./resources/js/@core/components/CardStatisticsVerticalSimple.vue')['default']
    ConfirmDialog: typeof import('./resources/js/@core/components/ConfirmDialog.vue')['default']
    CustomizerSection: typeof import('./resources/js/@core/components/CustomizerSection.vue')['default']
    DialogCloseBtn: typeof import('./resources/js/@core/components/DialogCloseBtn.vue')['default']
    EditAddressDialog: typeof import('./resources/js/@core/components/EditAddressDialog.vue')['default']
    EnableOneTimePasswordDialog: typeof import('./resources/js/@core/components/EnableOneTimePasswordDialog.vue')['default']
    ErrorHeader: typeof import('./resources/js/@core/components/ErrorHeader.vue')['default']
    I18n: typeof import('./resources/js/@core/components/I18n.vue')['default']
    Notifications: typeof import('./resources/js/@core/components/Notifications.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shortcuts: typeof import('./resources/js/@core/components/Shortcuts.vue')['default']
    TheCustomizer: typeof import('./resources/js/@core/components/TheCustomizer.vue')['default']
    ThemeSwitcher: typeof import('./resources/js/@core/components/ThemeSwitcher.vue')['default']
    UserInfoEditDialog: typeof import('./resources/js/@core/components/UserInfoEditDialog.vue')['default']
    UserUpgradePlanDialog: typeof import('./resources/js/@core/components/UserUpgradePlanDialog.vue')['default']
  }
}
